"""0402_1

Revision ID: 1d2d54eba5e7
Revises: 9cd13f3d65e3
Create Date: 2026-04-02 12:17:32.435169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '1d2d54eba5e7'
down_revision: Union[str, Sequence[str], None] = '9cd13f3d65e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postlike',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('commentlike',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.add_column('comment', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('post', sa.Column('likes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'likes')
    op.drop_column('comment', 'likes')
    op.drop_table('commentlike')
    op.drop_table('postlike')
    # ### end Alembic commands ###
