"""add image_url to chat_message

Revision ID: 235c914e1c7c
Revises: 37c54c0ec081
Create Date: 2026-08-06 14:29:11.579516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '235c914e1c7c'
down_revision: Union[str, Sequence[str], None] = '37c54c0ec081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'image_url')
    # ### end Alembic commands ###
