"""recurring health schedules

Revision ID: 37c54c0ec081
Revises: a1b2c3d4e5f6
Create Date: 2026-08-06 02:57:05.586222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37c54c0ec081'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_completion',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['health_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'completed_date')
    )
    op.add_column('health_schedule', sa.Column('scheduled_time', sa.Time(), nullable=False))
    op.add_column('health_schedule', sa.Column('scheduled_date', sa.Date(), nullable=True))
    op.add_column('health_schedule', sa.Column('repeat_days', sqlmodel.sql.sqltypes.AutoString(length=13), nullable=True))
    op.add_column('health_schedule', sa.Column('start_date', sa.Date(), nullable=True))
    op.drop_column('health_schedule', 'scheduled_at')
    op.drop_column('health_schedule', 'is_done')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_schedule', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('health_schedule', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('health_schedule', 'start_date')
    op.drop_column('health_schedule', 'repeat_days')
    op.drop_column('health_schedule', 'scheduled_date')
    op.drop_column('health_schedule', 'scheduled_time')
    op.drop_table('schedule_completion')
    # ### end Alembic commands ###
