"""add report handling status

Revision ID: 3f323fbb3c1f
Revises: 4b9f000f24bc
Create Date: 2026-08-15 02:50:59.887204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '3f323fbb3c1f'
down_revision: Union[str, Sequence[str], None] = '4b9f000f24bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 이미 쌓인 신고는 아직 아무도 처리하지 않았으므로 pending이다.
    # server_default 없이 NOT NULL을 붙이면 기존 행 때문에 실패한다.
    op.add_column(
        'report',
        sa.Column(
            'status',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='pending',
        ),
    )
    # 기본값은 채워 넣기용이라 남겨두지 않는다. 값은 앱이 항상 넣는다.
    op.alter_column('report', 'status', server_default=None)
    op.add_column('report', sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('report', sa.Column('handled_by', sa.Integer(), nullable=True))
    op.add_column('report', sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'report', 'user', ['handled_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'handled_at')
    op.drop_column('report', 'handled_by')
    op.drop_column('report', 'action')
    op.drop_column('report', 'status')
    # ### end Alembic commands ###
