"""merge reports into one table with snapshot

Revision ID: 4b9f000f24bc
Revises: 53e344a46ab9
Create Date: 2026-08-15 02:19:45.291865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b9f000f24bc'
down_revision: Union[str, Sequence[str], None] = '53e344a46ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_content', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('target_author_id', sa.Integer(), nullable=False),
    sa.Column('target_author_nickname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'target_type', 'target_id')
    )

    # 기존 신고를 옮긴다. 옮기지 않으면 이미 접수된 신고가 사라진다.
    #
    # 사본은 원래 신고 시점이 아니라 지금의 내용으로 채운다. 그때 무엇이
    # 적혀 있었는지는 남아 있지 않다. 대상이 이미 지워진 신고는 CASCADE로
    # 함께 사라졌으므로 옮길 것도 없다.
    op.execute("""
        INSERT INTO report (
            reporter_id, target_type, target_id, reason,
            target_content, target_author_id, target_author_nickname,
            target_group_id, created_at
        )
        SELECT
            r.reporter_id, 'post', r.post_id, LOWER(r.reason::text),
            LEFT(p.title, 1000), p.author_id, p.author_nickname,
            p.group_id, r.created_at
        FROM postreport r
        JOIN post p ON p.id = r.post_id
    """)
    op.execute("""
        INSERT INTO report (
            reporter_id, target_type, target_id, reason,
            target_content, target_author_id, target_author_nickname,
            target_group_id, created_at
        )
        SELECT
            r.reporter_id, 'comment', r.comment_id, LOWER(r.reason::text),
            LEFT(c.content, 1000), c.author_id, c.author_nickname,
            p.group_id, r.created_at
        FROM commentreport r
        JOIN comment c ON c.id = r.comment_id
        JOIN post p ON p.id = c.post_id
    """)

    op.drop_table('commentreport')
    op.drop_table('postreport')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postreport',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', postgresql.ENUM('SPAM', 'HATE', 'SEXUAL', 'SELF_HARM', 'PRIVACY', 'OTHER', name='reportreason'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('postreport_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], name=op.f('postreport_reporter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('postreport_pkey')),
    sa.UniqueConstraint('reporter_id', 'post_id', name=op.f('postreport_reporter_id_post_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('commentreport',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', postgresql.ENUM('SPAM', 'HATE', 'SEXUAL', 'SELF_HARM', 'PRIVACY', 'OTHER', name='reportreason'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('commentreport_comment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], name=op.f('commentreport_reporter_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('commentreport_pkey')),
    sa.UniqueConstraint('reporter_id', 'comment_id', name=op.f('commentreport_reporter_id_comment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('report')
    # ### end Alembic commands ###
