"""drop group notice column

Revision ID: 66dbd411e028
Revises: bffcd43f1f7d
Create Date: 2026-08-16 16:59:39.732277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '66dbd411e028'
down_revision: Union[str, Sequence[str], None] = 'bffcd43f1f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'notice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('notice', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
