"""0428-1

Revision ID: 8b948b93c688
Revises: 9e8399a76c4c
Create Date: 2026-04-28 11:57:18.134253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '8b948b93c688'
down_revision: Union[str, Sequence[str], None] = '9e8399a76c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###
