"""psql

Revision ID: b9b5478b661a
Revises: 1d2d54eba5e7
Create Date: 2026-04-02 15:00:42.237513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b9b5478b661a'
down_revision: Union[str, Sequence[str], None] = '1d2d54eba5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('suspended_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'suspended_until')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
