"""add post is_notice

Revision ID: bffcd43f1f7d
Revises: 3f323fbb3c1f
Create Date: 2026-08-16 10:00:40.542700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'bffcd43f1f7d'
down_revision: Union[str, Sequence[str], None] = '3f323fbb3c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 글은 공지가 아니다. server_default 없이 NOT NULL을 붙이면
    # 이미 있는 행 때문에 실패한다.
    op.add_column(
        'post',
        sa.Column('is_notice', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # 채워 넣기용 기본값은 남기지 않는다. 값은 앱이 항상 넣는다.
    op.alter_column('post', 'is_notice', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_notice')
    # ### end Alembic commands ###
