"""0512

Revision ID: c5a2cc90816b
Revises: 8b948b93c688
Create Date: 2026-05-12 11:17:01.583971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5a2cc90816b'
down_revision: Union[str, Sequence[str], None] = '8b948b93c688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('comment_post_id_fkey'), 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('commentlike_comment_id_fkey'), 'commentlike', type_='foreignkey')
    op.create_foreign_key(None, 'commentlike', 'comment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.add_column('post', sa.Column('is_anonymous', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('postcontent_post_id_fkey'), 'postcontent', type_='foreignkey')
    op.create_foreign_key(None, 'postcontent', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('postlike_post_id_fkey'), 'postlike', type_='foreignkey')
    op.create_foreign_key(None, 'postlike', 'post', ['post_id'], ['id'], ondelete='CASCADE')
    op.add_column('uploadlog', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_uploadlog_url'), 'uploadlog', ['url'], unique=False)
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('default_anonymous', sa.Boolean(), nullable=False))
    op.alter_column('user', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('user', 'default_anonymous')
    op.drop_column('user', 'is_deleted')
    op.drop_index(op.f('ix_uploadlog_url'), table_name='uploadlog')
    op.drop_column('uploadlog', 'url')
    op.drop_constraint(None, 'postlike', type_='foreignkey')
    op.create_foreign_key(op.f('postlike_post_id_fkey'), 'postlike', 'post', ['post_id'], ['id'])
    op.drop_constraint(None, 'postcontent', type_='foreignkey')
    op.create_foreign_key(op.f('postcontent_post_id_fkey'), 'postcontent', 'post', ['post_id'], ['id'])
    op.drop_column('post', 'is_anonymous')
    op.drop_constraint(None, 'commentlike', type_='foreignkey')
    op.create_foreign_key(op.f('commentlike_comment_id_fkey'), 'commentlike', 'comment', ['comment_id'], ['id'])
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key(op.f('comment_post_id_fkey'), 'comment', 'post', ['post_id'], ['id'])
    op.drop_column('comment', 'is_anonymous')
    # ### end Alembic commands ###
