"""add created_at to userblock

Revision ID: d7d28da90e8f
Revises: 235c914e1c7c
Create Date: 2026-08-06 15:22:45.516210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'd7d28da90e8f'
down_revision: Union[str, Sequence[str], None] = '235c914e1c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 이미 있는 차단 기록에는 시각이 없다. 지금 시각을 넣어두면 그 이전 대화는
    # 계속 보이므로, 기존 사용자에게 대화가 갑자기 사라지는 일이 없다.
    op.add_column(
        'userblock',
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text('now()'),
        ),
    )
    # 채워 넣기용이었으므로 기본값은 걷어낸다. 이후 값은 애플리케이션이 넣는다.
    op.alter_column('userblock', 'created_at', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userblock', 'created_at')
    # ### end Alembic commands ###
